name: Main
on:
    push:
        branches: [master]
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install dependencies
              run: npm install
            - name: Make env
              run: cp .env.example .env
            - name: Run test
              run: npm test
